### ISSUE TITLE
"Object of type AntonioSiles\\Nova4CardMap\\Nova4CardMap is not callable"

### ISSUE THREAD

**Issue by heshammostafa123** [antoniosiles/nova-4-card-map-plus#1]
When trying to use the card, it gives me this error inside Nova dashboard 

"Object of type AntonioSiles\\Nova4CardMap\\Nova4CardMap is not callable"

**Comment by antoniosiles** [comment]
Hello, does the error I mentioned persist or have you been able to solve the problem?
